### ISSUE TITLE
运行demo报错 是不是谷歌后台把项目删掉了

### ISSUE THREAD

**Issue by shangqianglong** [ChenYiHong930921/example-demo#4]
Execution failed for task ':app:processExampleFlavorDebugGoogleServices'.
> No matching client found for package name 'com.chenyihong.exampledflavordemo'

**Comment by ChenYiHong930921** [comment]
才看到，buildVariant选originDebug或originRelease就行了。

**Comment by ChenYiHong930921** [comment]
> Execution failed for task ':app:processExampleFlavorDebugGoogleServices'.
> 
> > No matching client found for package name 'com.chenyihong.exampledflavordemo'

才看到，buildVariant选originDebug或originRelease就行了。
